#!/usr/bin/env python

"""
Fit an eccentric waveform using SEOBNRv4E, using fitted optimal parameters.
Should be called on a SimulationAnnex directory, where it will read mass ratio
and spins, and the waveform to be fit.

Outputs a pdf with diagnostics and final fits, as well as printing the final
time to merger.
"""

from __future__ import division
from __future__ import print_function

import os
import argparse
import h5py as h5

import matplotlib
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
import numpy as np
import scipy

matplotlib.rcParams["mathtext.fontset"] = "stix"
matplotlib.rcParams["font.family"] = "STIXGeneral"
matplotlib.rcParams["axes.linewidth"] = 1  # set the value globally
plt.rcParams["figure.figsize"] = (14, 10)
plt.rcParams["font.size"] = "18"

import argparse
import os

from scipy.interpolate import InterpolatedUnivariateSpline
import lal, lalsimulation
from scipy.optimize import minimize
from scipy.optimize import Bounds


# Some functions to plot the time domain modes
def AmpPhysicaltoNRTD(ampphysical, M, dMpc):
    return ampphysical * dMpc * 1e6 * lal.PC_SI / (lal.C_SI * (M * lal.MTSUN_SI))


def compute_freqInterp(time, hlm):
    philm = np.unwrap(np.angle(hlm))

    intrp = InterpolatedUnivariateSpline(time, philm)
    omegalm = intrp.derivative()(time)

    return omegalm


def SectotimeM(seconds, M):
    return seconds / (M * lal.MTSUN_SI)


# Function to compute amplitude, phase and frequency difference


def compute_phase_amp_om_diff(
    timeNRv4EHM,
    amplmv4EHM,
    phaselmv4EHM,
    omegalmv4EHM,
    timeNRv4HM,
    amplmv4HM,
    phaselmv4HM,
    omegalmv4HM,
    mode_list,
    align_start=True,
):
    timeCommon = {}
    phidiff = {}
    omdiff = {}
    ampdiff = {}
    for l, m in mode_list:
        # print(l,m)
        ttv4EHM = timeNRv4EHM
        ampv4EHM = amplmv4EHM[l, m]
        phv4EHM = phaselmv4EHM[l, m]
        omv4EHM = omegalmv4EHM[l, m]

        ttv4HM = timeNRv4HM
        ampv4HM = amplmv4HM[l, m]
        phv4HM = phaselmv4HM[l, m]
        omv4HM = omegalmv4HM[l, m]

        dtv4E = ttv4EHM[-1] - ttv4EHM[-2]
        dtv4 = ttv4HM[-1] - ttv4HM[-2]
        dt = min(dtv4E, dtv4)

        t0v4 = ttv4HM[0]
        t0v4E = ttv4EHM[0]

        tmin = max(t0v4, t0v4E)
        tmax = min(ttv4HM[-1], ttv4EHM[-1])

        timeCommon = np.arange(tmin, tmax, dt)

        iphv4 = InterpolatedUnivariateSpline(ttv4HM, phv4HM)
        iomv4 = InterpolatedUnivariateSpline(ttv4HM, omv4HM)
        iampv4 = InterpolatedUnivariateSpline(ttv4HM, ampv4HM)

        iphv4E = InterpolatedUnivariateSpline(ttv4EHM, phv4EHM)
        iomv4E = InterpolatedUnivariateSpline(ttv4EHM, omv4EHM)
        iampv4E = InterpolatedUnivariateSpline(ttv4EHM, ampv4EHM)

        if align_start == True:
            delta_phi0 = -iphv4(tmin) + iphv4E(tmin)

        else:
            tAlign = 0
            delta_phi0 = -iphv4(tAlign) + iphv4E(tAlign)

        phidiff[l, m] = iphv4E(timeCommon) - (iphv4(timeCommon) + delta_phi0)
        ampdiff[l, m] = iampv4E(timeCommon) - iampv4(timeCommon)
        omdiff[l, m] = iomv4E(timeCommon) - iomv4(timeCommon)

    return timeCommon, phidiff, omdiff, ampdiff


def waveform_to_frequency(waveform_dict):
    return -np.diff(np.unwrap(np.angle(waveform_dict["hlm"][(2, 2)]))) / np.diff(
        waveform_dict["t"]
    )


def compute_deriv_f(time, f):
    intrp = InterpolatedUnivariateSpline(time, f)
    deriv = intrp.derivative()(time)

    return deriv


def compute_deriv_f(time, f):
    intrp = InterpolatedUnivariateSpline(time, f)
    deriv = intrp.derivative()(time)

    return deriv


def first_two_extrema(data):
    extrema = np.nonzero(np.diff(np.sign(np.diff(data))))
    return extrema[0][:2]


# Generate modes in NR units (rescaled by total mass of the system)
def SEOBNRv4EHM_modes_lightweight(
    q: float,
    chi1: float,
    chi2: float,
    eccentricity: float,
    eccentric_anomaly: float,
    f_min: float,
    M_fed: float,
    delta_t: float,
    EccIC: int,
):
    # Some internal parameters of the model
    HypPphi0, HypR0, HypE0 = [0.0, 0, 0]

    EccFphiPNorder = 99
    EccFrPNorder = 99
    EccWaveformPNorder = 16
    EccBeta = 0.09
    Ecct0 = 100

    EccPNFactorizedForm = (
        EccNQCWaveform
    ) = EccPNRRForm = EccPNWfForm = EccAvNQCWaveform = 1
    EcctAppend = 40

    m1 = q / (1 + q) * M_fed
    m2 = 1 / (1 + q) * M_fed
    dMpc = 500
    dist = dMpc * (1e6 * lal.PC_SI)

    SpinAlignedVersion = 41
    ellMaxForNyquistCheck = 5
    nqcCoeffsInput = lal.CreateREAL8Vector(
        50
    )  ##This will be unused, but it is necessary

    sphtseries, dyn, dynHi = lalsimulation.SimIMRSpinAlignedEOBModesEcc_opt1(
        delta_t,
        m1 * lal.MSUN_SI,
        m2 * lal.MSUN_SI,
        f_min,
        dist,
        chi1,
        chi2,
        eccentricity,
        eccentric_anomaly,
        SpinAlignedVersion,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
        nqcCoeffsInput,
        0,
        EccFphiPNorder,
        EccFrPNorder,
        EccWaveformPNorder,
        EccPNFactorizedForm,
        EccBeta,
        Ecct0,
        EccNQCWaveform,
        EccPNRRForm,
        EccPNWfForm,
        EccAvNQCWaveform,
        EcctAppend,
        EccIC,
        HypPphi0,
        HypR0,
        HypE0,
        ellMaxForNyquistCheck,
        0.0,
    )

    hlm = {}

    ##22 mode
    modeL = sphtseries.next.next.next.next.l
    modeM = sphtseries.next.next.next.next.m
    h22 = sphtseries.next.next.next.next.mode.data.data  # This is h_22
    hlm[modeL, modeM] = AmpPhysicaltoNRTD(h22, M_fed, dMpc)
    hlm[modeL, -modeM] = ((-1) ** modeL) * np.conjugate(hlm[modeL, modeM])

    time_array = np.arange(0, len(hlm[2, 2]) * delta_t, delta_t)
    timeNR = SectotimeM(time_array, M_fed)

    imax = np.argmax(np.abs(hlm[2, 2]))
    timeNR -= timeNR[imax]

    return (
        timeNR,
        hlm,
    )


# Function to minimise over.
# def func(t, ecc, f_min):
#     (
#         timeNRv4EHM,
#         hlmv4EHM,
#     ) = SEOBNRv4EHM_modes_lightweight(
#         q,
#         chi1,
#         chi2,
#         ecc,
#         ecc_anomaly,
#         f_min,
#         Mtot,
#         delta_t,
#         EccIC,
#     )
#     A_22_eob = np.abs(hlmv4EHM[2, 2])
#     A_22_eob_interp = scipy.interpolate.interp1d(timeNRv4EHM - timeNRv4EHM[0], A_22_eob)
#     plt.figure(figsize=(8, 6))
#     plt.plot(t, A_22_eob_interp(t), label="Function Evaluation")
#     plt.plot(t, A22_NR, label="NR")
#     plt.title(f"ecc_change = {ecc:.3}, fmin_change = {f_min:.3}")
#     plt.grid()
#     plt.legend()
#     plt.tight_layout()
#     pdf.savefig()
#     plt.close()
#     return A_22_eob_interp(t)


def func(dt_ecc_fmin):
    (
        timeNRv4EHM,
        hlmv4EHM,
    ) = SEOBNRv4EHM_modes_lightweight(
        q,
        chi1,
        chi2,
        dt_ecc_fmin[1],
        ecc_anomaly,
        dt_ecc_fmin[2],
        Mtot,
        delta_t,
        EccIC,
    )
    A_22_eob = np.abs(hlmv4EHM[2, 2])
    A_22_eob_interp = scipy.interpolate.interp1d(
        timeNRv4EHM - timeNRv4EHM[0] - dt_ecc_fmin[0], A_22_eob
    )
    plt.figure(figsize=(8, 6))
    plt.plot(t_NR, A_22_eob_interp(t_NR), label="Function Evaluation")
    plt.plot(t_NR, A22_NR, label="NR")
    plt.title(
        f"dt = {dt_ecc_fmin[0]:.3}, ecc = {dt_ecc_fmin[1]:.3}, fmin = {dt_ecc_fmin[2]:.3}"
    )
    plt.grid()
    plt.legend()
    plt.tight_layout()
    pdf.savefig()
    plt.close()
    np.sqrt(np.sum((A_22_eob_interp(t_NR) - A22_NR) ** 2.0) / t_NR.size)
    result = np.sqrt(np.sum((A_22_eob_interp(t_NR) - A22_NR) ** 2.0) / t_NR.size)
    print(result)
    return result


def final_call(dt_ecc_fmin):
    (
        timeNRv4EHM,
        hlmv4EHM,
    ) = SEOBNRv4EHM_modes_lightweight(
        q,
        chi1,
        chi2,
        dt_ecc_fmin[1],
        ecc_anomaly,
        dt_ecc_fmin[2],
        Mtot,
        delta_t,
        EccIC,
    )
    A_22_eob = np.abs(hlmv4EHM[2, 2])
    A_22_eob_interp = scipy.interpolate.interp1d(
        timeNRv4EHM - timeNRv4EHM[0] - dt_ecc_fmin[0], A_22_eob
    )
    plt.figure(figsize=(8, 6))
    plt.plot(t_NR, A_22_eob_interp(t_NR), label="Function Evaluation")
    plt.plot(t_NR, A22_NR, label="NR")
    plt.title(
        f"dt = {dt_ecc_fmin[0]:.3}, ecc = {dt_ecc_fmin[1]:.3}, fmin = {dt_ecc_fmin[2]:.3}"
    )
    plt.grid()
    plt.legend()
    plt.tight_layout()
    pdf.savefig()
    plt.close()
    return np.abs(timeNRv4EHM[0])


# ===============================================================
if __name__ == "__main__":
    p = argparse.ArgumentParser(usage=__doc__)
    p.add_argument(
        "--dir",
        nargs=1,
        help="Path to rh_FiniteRadii_CodeUnits.h5",
    )
    p.add_argument(
        "--out",
        default="summary.pdf",
        help="Output filename of the generated pdf-plots",
    )
    p.add_argument(
        "--q",
        type=float,
        help="Mass ratio.",
    )
    p.add_argument(
        "--spin1",
        type=float,
        help="Spin of primary BH.",
    )
    p.add_argument(
        "--spin2",
        type=float,
        help="Spin of secondary BH.",
    )
    p.add_argument(
        "--e0",
        type=float,
        help="Eccentricity initial guess.",
    )
    p.add_argument(
        "--f0",
        type=float,
        help="Frequency initial guess.",
    )
    args = p.parse_args()

    # Load NR waveform
    waveform_file = h5.File(
        args.dir[0],
        "r",
    )
    extraction_radius = int(list(waveform_file.keys())[0][1:5])
    waveform = waveform_file[list(waveform_file.keys())[0]]["Y_l2_m2.dat"]
    t = waveform[:, 0]
    A22 = np.sqrt(waveform[:, 1] ** 2.0 + waveform[:, 2] ** 2.0)

    t_index = np.argmin(np.abs(t - 200 - extraction_radius))

    extrema_index = first_two_extrema(A22[t_index:])
    half_orbit = t[extrema_index[1]] - t[extrema_index[0]]
    start_index = np.argmin(np.abs(t - t[extrema_index[0]] - half_orbit))
    A22_NR = A22[start_index:]
    t_NR = t[start_index:]
    t_NR = t_NR - t_NR[0]

    q = args.q
    chi1, chi2 = (
        args.spin1,
        args.spin2,
    )
    Mtot = 40.0
    delta_t = 1.0 / (4096.0) / 2.0
    EccIC = -2
    ecc_anomaly = np.pi
    pdf = PdfPages(args.out)

    xtol, gtol, ftol = 1e-15, 1e-15, 1e-15
    initial_guess = np.array([100.0, args.e0, args.f0])

    # popt, pcov = curve_fit(
    #     func,
    #     t_NR,
    #     A22_NR,
    #     p0=initial_guess,
    #     method="trf",
    #     gtol=gtol,
    #     xtol=xtol,
    #     ftol=ftol,
    #     verbose=2,
    #     diff_step=np.array([0.2, 0.1]),
    # )
    # eob_merger = final_call(*popt)
    bounds = Bounds(np.array([0.0, 0.0, 6.0]), np.array([200.0, 0.999, 20.0]))

    tol = 1e-6
    res = minimize(
        func,
        initial_guess,
        method="Nelder-Mead",
        bounds=bounds,
        tol=tol,
        options={"disp": True},
    )

    merger_time = final_call(res.x)

    pdf.close()
    print(f"EOB merger time was {merger_time}")
    print("EOB parameters are:")

    print(res.x)

    os.sys.exit(0)

###########################################
